travis:
  secure:
    BINSTAR_TOKEN: yulRJk3uwIrUmLSn+2S2dOlGY8jk/oglM/kL1u5AyNLJMVEZWO/zEtdAwWDEQQxQoRPozWaRWnCbhTnMXpe7y5Gq3sbmShwW3aK3uU8JMMyEyBRi1JQSWapVO9AeBhotaF3fAJc3YrWBpJNum50fXIvq8wMx7groyZwbf2K/dELlaFI7RbN4N+rH04ENX8A+juI3zARaqVAik2JFa5BOMO1AzLjNW520VxDz81nT2dQEihHfvVvHri0rNIFaUjlXG1ASxA2EXST7dD7G2sc6FvAdaNDqiYeozxwN+hzo4P00HCogSwJWFuuUxBxInWnJkWY1apR0qFMptmDTFv/3aHqzZF3z2VY+NmrEHpyxvZ5K4M4FR7cFQeZoYMCxU0v52nlqHWz6EjAyMjsSj+wv7oqtLUoZ/h6Ows8tFhr/FSzcLZMPnxbFpaFFSQ0KY4HcZIGnDNmBwmT+7Cx26dS9fBD9v6/3b/A5HXc68OIXyxD+H/Fu1CCdXne9+4d8Oggfw2SH0pugNA+Aa0DhIpp9me8AJJWZORTxp1iSkTmJt69LHssohzgeTrcl4+A5iHERNp9hexBu3KpVZmAekHchV1DEoqsKo7sis/Pkw0ohz6Yg5TNCt7Hh4L8WrIuZjspTN27UKHvYKhDWFlWt2bnMxGJ3Kg6rsScqRoSRa1VWSPQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
