travis:
  secure:
    BINSTAR_TOKEN: ssYoJxBYvMScva+gu46EVgwX0iRVjLxGjTA/mPW1umfqEAsg/tuQTqkHRNydeq2/fwsWGRw3YwgY/oex3JgXhSNukBvZb1IbjuOUpSYXyx3f4m8HFtHPYL+mQZaPnAWUovKOAHfzjjut9O1DcxmpQHxyziqA8EfQVO5l58I0zKziJtdby5+REjQnxC/ZifLe9mQr7R9GH2gmSqTnUgpDH+Gdb8I90I/O5Z7czZtV1KbbqJd7sMgrn3iMBph9GRzLCZSCDK9FrO6YO1LBAeCAQEjPckoL9rTwAvCBEzX3Osb48//wH8AfhHqoDabOE4LaxDnYczeTOaMDxQ4Xa0Grhx32reyEnrArTCWqWs5pcW+1DMxBgXTLv30zb6ap+GThDss6xZtvIuZBaN+5odhX2Yd/K1+zUUO89xdr8BUsVQWH8XpfDvV4XNt2vUHvSI4yIqVA1TwXJvs+bGuM4uYjY4XxFjtOmLc7+wX4zVG3yPKw3AuEsHvT6IMm8CMmhDE3/eaT/YxWh0cSvPuqYg8yZFknkr2RmwxiRSEpbZTbGxUfz1XUJa0fOcPd8JuDpih4cUYh9cpZfRmmC1oW27lnWEEm7Mezq6X2HiEMsN9nfWxtvQ9PMX72r0IGKDcnyNzS59HEsdJHLEPd8CbsZCnvW80P1Mw5M4DwMYDA1M4N3sc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
